config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#new"
  root 'dashboards#new'

  resources :dashboards do
    collection do
      post :select
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  def solver
    solver_id && Applicant.new(solver_id)
  end
end

app/models/applicant.rb
class Applicant
  attr_reader :id

  def initialize(id)
    @id = id
  end

  def self.new_id
    SecureRandom.uuid
  end

  def ==(other)
    other.id == id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/box.rb
class Box
  attr_reader :position

  def initialize(position, answer)
    @position = position
    @answer = answer
  end

  def answered?
    TouchedPosition.exists?(
      position: position,
      answer: answer,
    )
  end

  def dom_id
    "box_#{position}"
  end

  private

  attr_reader :answer, :answerer_id
end

app/models/game.rb
# ゲームの状態を表す
class Game
  attr_reader :state

  def initialize
    @state = nil
  end

  def detect_state
    @state = if Answer.all.empty? || Answer.last.solver.present?
                  SettingAnswerState.new
             else
                  InputtingSelectionState.new
             end
    self
  end

  def next(input, user)
    @state = @state.transpose(input, user)
  end

  def message
    @state.message
  end

  def view(user)
    @state.view(user)
  end

  def selector_view
    @state.selector_view
  end

  def answer
    @state.answer
  end

  def box_at(position)
    boxes[position - 1]
  end

  def boxes
    (1..9).map { |pos| Box.new(pos, answer) }
  end
end

app/models/inputting_selection_state.rb
class InputtingSelectionState
  def transpose(input, user)
    if input.to_i == Answer.last.position
      Answer.last.update(solver_id: user.id)
      SettingAnswerState.new
    else
      TouchedPosition.create(answerer_id: user.id, position: input, answer: Answer.last)
      InputtingSelectionState.new
    end
  end

  def view(_user)
    'select'
  end

  def message
    { alert: "不正解" }
  end

  def answer
    Answer.last
  end
end

app/models/setting_answer_state.rb
class SettingAnswerState
  def transpose(input, _user)
    Answer.create!(position: input)
    InputtingSelectionState.new
  end

  def view(user)
    if Answer.all.empty? || user == Answer.last.solver
      'new'
    else
      'wait'
    end
  end

  def message
    { notice: "正解です!" }
  end

  def answer
    Answer.new
  end
end

app/models/touched_position.rb
class TouchedPosition < ApplicationRecord
  belongs_to :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    id = session[:applicant_id]
    if id.blank?
      id = Applicant.new_id
      session[:applicant_id] = id
    end
    Applicant.new(id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def new
    game = Game.new.detect_state
    @boxes = game.boxes

    render game.view(current_user)
  end

  def show
    redirect_to new_dashboard_path
  end

  def select
    game = Game.new.detect_state
    box = game.box_at(params[:position].to_i)
    game.next(box.position, current_user)

    game.boxes.each do |b|
      Turbo::StreamsChannel.broadcast_replace_to(
        :boxes, target: b.dom_id, partial: "dashboards/box", locals: { b: b }
      )
    end
    respond_to do |format|
      format.html { redirect_to new_dashboard_path, **game.message }
    end
  end

  def create
    Answer.create(position: params[:new_answer])
    redirect_to new_dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include HtmlClass::Dsl
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_box.html.erb
<div id="<%= b.dom_id %>" class="<%= html_class "
            h-32 w-32
            flex justify-center items-center rounded-md bg-white shadow-md
            transform hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-xl
      ", "bg-pink-100": -> { b.answered?} %>">
  <p class="bold">box <%= b.position %></p>
</div>

app/views/dashboards/_boxes.html.erb
<div class="grid grid-cols-3 gap-4 mt-10" id="boxes">
  <% boxes.each do |b| %>
    <%= button_to path, params: {key => b.position}, method: :post, form_class: "mx-auto" do %>
      <%= render 'box', b: b %>
    <% end %>
  <% end %>
</div>

app/views/dashboards/_message.html.erb
<div class="bg-white border border-gray-400 rounded-md p-3">
  <%= message %>
</div>

app/views/dashboards/new.html.erb
<main>
  <%= turbo_stream_from :boxes %>
  <%= render 'message', message: "新しい正解を設定するため、箱を一つ選んでください。" %>
  <%= render 'boxes', path: dashboards_path, key: :new_answer, boxes: @boxes %>
</main>

app/views/dashboards/select.html.erb
<main>
  <%= turbo_stream_from :boxes %>
  <%= render 'message', message: "どこかのだれかが、9個の箱のなかの1つを正解として設定しました。正解の箱を選んでください。" %>
  <%= render 'boxes', path: select_dashboards_path, key: :position, boxes: @boxes %>
</main>

app/views/dashboards/wait.html.erb
<main>
  <%= render 'message', message: :"解答設定中。お待ち下さい。" %>
</main>

app/views/layouts/_header.html.erb
<header class="bg-indigo-50 pb-2">
  <nav class="flex justify-between container mx-auto ">
    <%= link_to "nine boxes", root_path, class: "font-bold" %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nine boxes</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_importmap_tags %>
</head>

<body class="bg-blue-200 text-gray-700">

<%= render 'layouts/header' %>
<div class="mx-auto">
  <% if notice.present? %>
    <p class="bg-green-100 text-gray-600 p-2"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="bg-red-200 text-gray-600 p-2"><%= alert %></p>
  <% end %>
</div>
<div class="container mx-auto mt-10">
  <%= yield %>
</div>
</body>
</html>